### ISSUE TITLE
gemma + media pipeline

### ISSUE THREAD

**Issue by hemanth** [google-deepmind/gemma#22]
I am using `@mediapipe/tasks-genai/wasm` and generating the response. 

Missing context? 

https://github.com/google-deepmind/gemma/assets/18315/06a36d83-dc07-426d-9fd9-57d7c7813049

**Comment by Linchenn** [comment]
Hi @hemanth ,

The Mediapipe LLM Web API does not help you keep the context, but offers the flexibility to developers to add context within conversation.

## Approach
After the first question, you could combine all the previous answers, previous questions, and the current question you want to ask into one prompt. Also, some LLM hint-tag helps LLM understand your prompt (eg. <start_of_turn> and <end_of_turn> for Gemma).

For example:
Assume you had the following conversation:
```
You: Hello!
Gemma: 1. Hello to you too! 👋  What would you like to talk about today? 😊
```
Then, you want to ask a new question `How are you?`, so you could build a new prompt for it, like:
```
<start_of_turn>user
Hello!<end_of_turn>
<start_of_turn>model
1. Hello to you too! 👋  What would you like to talk about today? 😊<end_of_turn>
<start_of_turn>user
How are you?<end_of_turn>
<start_of_turn>model
```

## Extend window size
When you create the LLM Inference task, you could set `maxTokens `, which defines the max num of tokens of your prompt. You may want to extend it larger than the default (512), because I saw LLM's answer to your question is relatively long.

**Comment by hemanth** [comment]
@Linchenn Thanks for the detailed reply, is there a jsfiddle link for the same? 

Also, the template `<start_of_turn>` is defined somewhere?

**Comment by gustheman** [comment]
The template is explained here: https://ai.google.dev/gemma/docs/formatting

**Comment by Linchenn** [comment]
> is there a jsfiddle link for the same?

I don't think we have it yet.

**Comment by hemanth** [comment]
Works fine, thank you. (I had tried fetching gemma from HF back then and had used the base template to fromat) 

<img width="1052" alt="image" src="https://github.com/user-attachments/assets/3e51d4ac-12cf-4919-93a5-c1c868b52b1f">
