### ISSUE TITLE
Why does model.safetenors.index.json not have lm_head.weight?

### ISSUE THREAD

**Issue by Minami-su** [google-deepmind/gemma#8]

**Comment by JLM-Z** [comment]
lm_head.weight is tied to embedding

**Comment by Gopi-Uppari** [comment]
Hi @Minami-su,

**model.save_pretrained("google/gemma-2b", safe_serialization=False)**
If i save the model using safetensors then lm_head.weight parameter is not present in model.safetenors.index.json

**model.save_pretrained("google/gemma-2b", safe_serialization=True)**
But i save using .bin then lm_head.weight parameter is present in pytorch_model.bin.index.json 

The lm_head.weight is missing in safetensors because SafeTensors optimizes by tying the embedding weights (model.embed_tokens.weight) to the lm_head.weight. PyTorch .bin files store them separately for compatibility, but SafeTensors skips redundant storage to save space and improve efficiency.

Thank you.

**Comment by tilakrayal** [comment]
Closing this issue due to lack of recent activity,  Please feel free reopen if this is still a valid request. Thank you!
